@startuml コンビニ
|客|
|客|
|店員|
|店員|

|客|
start
:弁当をレジに持っていく;
|客|
|店員|
fork
|店員|

if (温めますか？) then (yes)
  :弁当を温める;
else (no)
  
  endif
|店員|
:弁当を袋に入れる;
|客|
:お金を支払う;
|客|
|店員|
:清算する;

fork
:弁当を手に持つ;
stop
@enduml
