@startuml レストラン

|顧客|
start

|顧客|
:案内を依頼する;
|給仕|
:テーブルに案内する;
|給仕|
:メニューを渡す;
fork
  |顧客|
  :注文を決める;
  fork again
    |顧客|
    :注文を受ける;
    |給仕|
    :伝票を書く;
    |給仕|
    :料理人に注文を伝える;
    fork again
      |料理人|
      :注文を受ける;
      |料理人|
      :料理を作る;
      |料理人|
      :料理を運ぶ;
    |給仕|
    :伝票を渡す;
  end fork
  |顧客|
  :料理を食べる;
  |顧客|
  :代金を払う;
|給仕|
:伝票を受け取る;
stop

@enduml
