@startuml 診察予約
skinparam state {
    StartColor DeepSkyBlue
    EndColor DarkSeaGreen
}

[*] --> メニュー画面
メニュー画面 --> 予約と確認画面 : 予約
予約と確認画面 --> あなたの順番画面 : 登録
予約と確認画面 --> あなたの順番画面 : 確認
予約と確認画面 --> メニュー画面 : 取消
あなたの順番画面 --> 予約と確認画面 : 戻る
あなたの順番画面 --> 今の順番画面 : 診察中
今の順番画面 --> あなたの順番画面 : 診察終了
今の順番画面 --> [*] : 全員診察終了
@enduml
