@startuml ライントレーサー
left to right direction
actor ユーザー as User
actor ライントレーサー as LineTracer

User --> (電源SWを入れる)
User --> (光センサーが黒いライン上にある)
User --> (光センサーがラインを外れる)
User --> (電源SWを切る)

(電源SWを入れる) --> (システム起動)
(光センサーが黒いライン上にある) --> (右旋回開始)
(光センサーがラインを外れる) --> (左旋回開始)
(システム起動) --> (ラインの右境界線上を進む)
(ラインの右境界線上を進む) --> (電源SWを切る)
(電源SWを切る) --> (システム停止)

@enduml
