@startuml 商品検索
skinparam classAttributeIconSize 0

package "Boundary" {
  class 商品検索画面 {
    +商品情報検索(商品番号) : 商品情報
  }
}

package "Control" {
  class 商品検索コントローラ {
    +商品登録()
    +商品カテゴリ作成()
    +商品カテゴリ設定()
    +商品情報表示()
  }
}

package "Entity" {
  class 商品 {
    -商品情報
    +商品情報取得() : 商品情報
  }

  class 商品カテゴリ {
    -商品カテゴリ
    +商品カテゴリ設定()
  }

  class 会員 {
    +商品検索画面
  }

  商品 --* 商品カテゴリ
  商品カテゴリ o-- 商品検索コントローラ
}

会員 -> 商品検索画面
商品検索画面 -> 商品検索コントローラ
@enduml
