@startuml 資格
class 情報処理安全確保支援士 {
    - 受験日時: 2020/10/21
    + 合格()
}

class LinuC試験 {
    - 試験レベル: Level1
    - 受験日時: 2021/3/28
    + 合格()
}

class 高橋洋平 {
    + 情報処理安全確保支援士
    + LinuC試験
}

class 樋口正之 {
    + 情報処理安全確保支援士
}
@enduml