@startuml 自販機

class 自動販売機 {
  - 販売機ID: int
  - 販売商品リスト: List<商品>
  - 現在の在庫: Map<商品, int>
  - 現在の売上額: int
  + 商品を追加する(商品: 商品, 在庫数: int): void
  + 商品を購入する(商品: 商品): void
  + 在庫を確認する(): Map<商品, int>
  + 売上額を確認する(): int
}

class ボタン {
  - ボタンID: int
  + ボタンを押す(): void
}

class 料金装置 {
  - 残高: int
  + 残高をチャージする(金額: int): void
  + 残高を確認する(): int
}

class ベンダー装置 {
  + 商品を配布する(商品: 商品): void
}

class 商品 {
  - 商品ID: int
  - 商品名: string
  - 価格: int
  + 商品IDを取得する(): int
  + 商品名を取得する(): string
  + 価格を取得する(): int
}

自動販売機 "1" *-- "1..*" 商品
自動販売機 "1" -- "1" ボタン
自動販売機 "1" -- "1" 料金装置
自動販売機 "1" -- "1" ベンダー装置

@enduml
