@startuml ライントレーサー
class ライントレーサー {
  - 光センサー : 光センサー
  - 右モータ : 右モータ
  - 左モータ : 左モータ
  - CPU : CPU
  - 電源SW : 電源SW

  + 起動() : void
  + 停止() : void
  + 黒い判定() : void
  + 明るい判定() : void
}

class 光センサー {
  + 黒い判定() : void
  + 明るい判定() : void
}

class 右モータ {
  + ON() : void
  + OFF() : void
}

class 左モータ {
  + ON() : void
  + OFF() : void
}

class CPU {}

class 電源SW {
  + 入れる() : void
  + 切る() : void
}

ライントレーサー --> 光センサー
ライントレーサー --> 右モータ
ライントレーサー --> 左モータ
ライントレーサー --> CPU
ライントレーサー --> 電源SW
@enduml