@startuml 自販機
skinparam sequenceArrowThickness 2

participant 客
participant 料金装置
participant ボタン
participant ベンダー装置

客 -> 料金装置: 金額を支払う
activate 料金装置

料金装置 -> ボタン: ドリンクを選択する
activate ボタン

ボタン -> ベンダー装置: ドリンクの注文を送信する
activate ベンダー装置

ベンダー装置 --> ボタン: 注文を確認する
deactivate ベンダー装置

ボタン --> 料金装置: 注文確認を返す
deactivate ボタン

料金装置 --> 客: 注文確認を通知する
deactivate 料金装置

客 -> ベンダー装置: ドリンクを受け取る
activate ベンダー装置
deactivate ベンダー装置

@enduml

