@startuml
start
:ユーザ名を入力する;
:パスワードを入力する;
if (認証が成功したか？) then (はい)
  :予約を行う;
else (いいえ)
  :ユーザ名とパスワードを再入力する;
  repeat
    :ユーザ名を入力する;
    :パスワードを入力する;
  repeat while (認証が成功するまで);
  :予約を行う;
endif
stop
@enduml
