@startuml 診察予約
actor User as User
actor Nurse as Nurse

rectangle "予約システム" {
    User --> (メニュー画面)
    (メニュー画面) --> (予約と確認画面) : リンク
    (予約と確認画面) --> (あなたの順番画面) : 登録
    (予約と確認画面) --> (あなたの順番画面) : 確認
    (予約と確認画面) --> (メニュー画面) : 取消
    Nurse --> (あなたの順番画面) : 順番表示
    Nurse --> (今の順番画面) : 順番表示
}

User <<-- Nurse : 順番更新

@enduml
