@startuml ライントレーサー
hide empty description

state 電源SW_OFF {
  [*] --> 電源SW_OFF
  電源SW_ON --> 電源SW_OFF
}

state 電源SW_ON {
  [*] --> 右旋回
  右旋回 --> 左旋回 : 光センサーがラインを外れる
  左旋回 --> 右旋回 : 光センサーが黒いライン上にある
  右旋回 --> 電源SW_OFF : 電源SWを切る
  左旋回 --> 電源SW_OFF : 電源SWを切る
  電源SW_OFF --> [*] : 電源SWを切る
  右旋回 --> ラインの右境界線上を進む : 光センサーが黒いライン上にある
  ラインの右境界線上を進む --> 電源SW_OFF : 電源SWを切る
}

電源SW_OFF --> 電源SW_ON : 電源SWを入れる

[*] --> 電源SW_OFF

@enduml
