@startuml 診察予約

scale 800 width

actor ユーザー as User

rectangle 予約システム {
  User --> (メニュー)
  User --> (予約と確認)
  User --> (あなたの順番)
  User --> (今の順番)
  
  (予約と確認) --> (あなたの順番) : 登録
  (予約と確認) --> (あなたの順番) : 確認
  (予約と確認) --> (メニュー) : 取消
  
  (メニュー) --> (予約と確認) : リンク
  (あなたの順番) --> (今の順番) : リンク
}

@enduml
