@startuml 商品
actor 受注係
boundary 注文登録画面
entity 商品
entity 注文

受注係 -> 注文登録画面 : 商品情報確認()
注文登録画面 -> 商品 : 商品情報取得()
商品 --> 注文登録画面 : 商品情報
注文登録画面 -> 注文登録画面 : 商品情報表示(商品情報)
注文登録画面 -> 注文登録画面 : 商品情報確認()
注文登録画面 -> 注文 : 商品登録(注文情報)
注文登録画面 -> 注文 : 注文オブジェクトを生成する()
@enduml
