@startuml 注文
class 顧客 {
    - 名前: 文字列
}

class 製品 {
    - 型式: 文字列
}

class 注文 {
    - 数量: 整数
}

class テレビ {
}

class 冷蔵庫 {
}

class プロジェクタ {
}

class 売り場 {
}

class ショップ {
    - 重要顧客: 顧客
    - 売り場: 売り場
    - 注文: 注文
}

顧客 --> ショップ
製品 --> 注文
注文 --> ショップ

テレビ --|> 製品
冷蔵庫 --|> 製品
プロジェクタ --|> 製品

売り場 --> ショップ
@enduml