@startuml 診察予約

scale 800 width

state メニュー {
  [*] --> メニュー画面
  メニュー画面 --> 予約と確認 : 予約機能へのリンク
  メニュー画面 --> あなたの順番 : 順番確認機能へのリンク
  メニュー画面 --> 今の順番 : 診察中患者の順番確認へのリンク
}

state 予約と確認 {
  [*] --> 予約と確認画面
  予約と確認画面 --> あなたの順番 : 登録ボタン押下
  予約と確認画面 --> あなたの順番 : 確認ボタン押下
  予約と確認画面 --> メニュー画面 : 取消ボタン押下
}

state あなたの順番 {
  [*] --> あなたの順番画面
}

state 今の順番 {
  [*] --> 今の順番画面
}

メニュー --> 予約と確認 : リンク
メニュー --> あなたの順番 : リンク
予約と確認 --> あなたの順番 : 登録
予約と確認 --> あなたの順番 : 確認
予約と確認 --> メニュー : 取消

@enduml
